brew/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', 'brew.views.brews'),
    url(r'^brews/$', 'brew.views.brews'),
    url(r'^brew_selection/$', 'brew.views.brew_selection'),
    url(r'^brew_data/$', 'brew.views.brew_data'),
    url(r'^brew_delete/(?P<pk>\d+)/$', 'brew.views.brew_delete'),
    url(r'^brews_delete_all/$', 'brew.views.brews_delete_all'),
    url(r'^brews_import/$', 'brew.views.brews_import'),
)

twisted_brew/urls.py
from django.conf.urls import patterns, include, url
from twisted_brew.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^index[/]$', home, name='home'),
    url(r'^home[/]$', home, name='home'),
    url(r'^commands[/]$', commands, name='commands'),
    url(r'^messages[/]$', MessageListView.as_view()),
    url(r'^warnings[/]$', WarningListView.as_view()),
    url(r'^errors[/]$', ErrorListView.as_view()),
    url(r'^messages_clear[/]$', messages_clear, name='messages_clear'),
    url(r'^message_head[/]$', message_head, name='message_head'),
    url(r'^message_rows/(?P<latest_timestamp>\d+)/(?P<max_rows>\d+)[/]$', message_rows, name='message_rows'),
    url(r'^message_delete/(?P<message_id>\d+)[/]$', message_delete, name='message_delete'),
    url(r'^message_fake/(?P<calling_page>\w+)/(?P<message_type>\w+)[/]$', message_fake, name='message_fake'),
    url(r'^charts[/]$', charts, name='charts'),
    url(r'^charts_update[/]$', charts_update, name='charts_update'),
    url(r'^ping_master[/]$', ping_master, name='ping_master'),
    url(r'^fetch_master_info[/]$', fetch_master_info, name='fetch_master_info'),
    url(r'^set_master_info[/]$', set_master_info, name='set_master_info'),
    (r'^brew/', include('brew.urls')),
    (r'^session/', include('session.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Django REST framework
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/', include('twisted_brew.api_v1_urls')),

    # Django Angular test
    url(r'^twistedbrew[/]$', twistedbrew, name='twistedbrew'),
)

brew/models.py
from django.db import models

COLUMN_SMALL_SIZE = 128


class Brew(models.Model):
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    brewer = models.CharField(max_length=COLUMN_SMALL_SIZE)
    style = models.CharField(max_length=COLUMN_SMALL_SIZE)
    category = models.CharField(max_length=COLUMN_SMALL_SIZE)
    description = models.TextField()
    profile = models.TextField()
    ingredients = models.TextField()
    web_link = models.CharField(max_length=COLUMN_SMALL_SIZE)

    def __str__(self):
        return '{0} ({1}) by {2}'.format(self.name, self.style, self.brewer)

    class Meta:
        ordering = ['name']


class BrewSection(models.Model):
    brew = models.ForeignKey('Brew')
    index = models.IntegerField()
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    worker_type = models.CharField(max_length=COLUMN_SMALL_SIZE)

    def __str__(self):
        return '{0} using {1}'.format(self.name, self.worker_type)

    class Meta:
        ordering = ['index']


class BrewStep(models.Model):
    SECONDS = 1
    MINUTES = 60
    HOURS = 60 * MINUTES
    DAYS = 24 * HOURS
    HOLD_TIME_UNITS = (
        (SECONDS, 'Seconds'),
        (MINUTES, 'Minutes'),
        (HOURS, 'Hours'),
        (DAYS, 'Days')
    )
    brew_section = models.ForeignKey('BrewSection')
    index = models.IntegerField()
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    unit = models.CharField(max_length=COLUMN_SMALL_SIZE)
    target = models.FloatField(max_length=COLUMN_SMALL_SIZE)
    hold_time = models.IntegerField(default=1)
    time_unit_seconds = models.IntegerField(choices=HOLD_TIME_UNITS, default=MINUTES)

    def __str__(self):
        return '{0} with target {1}'.format(self.name, self.target)

    class Meta:
        ordering = ['index']

brew/views.py
from django.core.context_processors import csrf
import os
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response
from brew.models import Brew, BrewSection, BrewStep
from brew.importing import brew_importer
import distribrewed.core.utils.logging as log
from rest_framework import viewsets
from brew.serializers import BrewSerializer, BrewSectionSerializer, BrewStepSerializer


class BrewViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows brews to be viewed or edited.
    """
    queryset = Brew.objects.all().order_by('name')
    serializer_class = BrewSerializer


class BrewSectionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows brew sections to be viewed or edited.
    """
    queryset = BrewSection.objects.all().order_by('index')
    serializer_class = BrewSectionSerializer


class BrewStepViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows brew steps to be viewed or edited.
    """
    queryset = BrewStep.objects.all().order_by('index')
    serializer_class = BrewStepSerializer


def brews(request):
    context = RequestContext(request)
    importers = brew_importer.BrewImporter.get_importers()
    context_dict = {
        'brews_active': True,
        'importers': importers,
    }
    context_dict.update(csrf(request))
    return render_to_response('brews.html', context_dict, context)


def brew_selection(request):
    if request.method == 'POST':
        brew_list = Brew.objects.order_by('name')
    else:
        brew_list = []
    return render_to_response('brew_selection.html', {'selection': brew_list})


def brew_data(request):
    if request.method == 'POST':
        brew = Brew.objects.get(pk=(request.POST['pk']))
    else:
        brew = None
    return render_to_response('brew_data.html', {'data': brew})


def brew_delete(request, pk):
    Brew.objects.get(pk=pk).delete()
    return HttpResponseRedirect('/brew/brews/')


def brews_delete_all(request):
    Brew.objects.all().delete()
    return HttpResponseRedirect('/brew/brews/')


def brews_import(request):
    uri = None
    try:
        if request.POST:
            index = int(request.POST['index'])
            file = request.FILES['file']
            filename = request.FILES['file'].name
            uri = os.path.dirname(os.path.realpath(__file__))
            uri += '/importing/uploaded_files/'
            uri += filename
            fd = open(uri, 'wb')
            for chunk in file.chunks():
                fd.write(chunk)
            fd.close()
            brew_importer.BrewImporter.import_brews(index, uri)
    except Exception as e:
        try:
            if uri is not None:
                log.error('Failed to upload file {0} : {1}'.format(uri, e.args[0]))
            else:
                log.error('Failed to upload file : {0}'.format(e.args[0]))
        except Exception:
            if uri is not None:
                log.error('Failed to upload file {0}'.format(uri))
            else:
                log.error('Failed to upload file')
    return HttpResponseRedirect('/brew/brews/')

brew/templates/brew_data.html
{% if data %}
<br />
<b>{{ data }}</b>
<ul>
    {% for brew_section in data.brewsection_set.all %}
    <li><i>{{ brew_section }}</i></li>
    <ol>
        {% for brew_step in brew_section.brewstep_set.all %}
        <li>{{ brew_step }}</li>
        {% empty %}
        <li>No steps found</li>
        {% endfor %}
    </ol>
    {% empty %}
    <li>No sections found</li>
    {% endfor %}
</ul>
<small><a href="/brew/brew_delete/{{ data.pk }}/">[delete]</a></small>
{% else %}
Brew not found
{% endif %}

brew/templates/brew_selection.html
<ul>
    {% for brew in selection %}
    <li><a onclick="get_brew_data({{ brew.pk }})">{{ brew.name }}</a></li>
    {% empty %}
    <li>No brews found</li>
    {% endfor %}
</ul>

brew/templates/brews.html
{% extends "base.html" %}

{% block content_heading %}
{% load static %}
<link href="{% static 'css/brew.css' %}" rel="stylesheet">
<script src="{% static 'js/brew.js' %}"></script>
<h2>Brews</h2>
{% csrf_token %}
{% endblock %}

{% block tb_sidebar_page_sidebar %}
<div class="brew_selection" id="brew_selection">

</div>
<div class="brew_import" id="brew_import">
    <div class="form-group">
        <br/><br/>
        <a class="btn btn-xs btn-danger" href="/brew/brews_delete_all/">delete all</a>
        <br/><br/>
        <form action="/brew/brews_import/" method="post" enctype="multipart/form-data" role="form">
            {% csrf_token %}
            {% if importers %}
            Import brews using<br/>
            <select name="index" class="form-control">
                {% for importer in importers %}
                <option value="{{ importer.index }}">{{ importer.display_name }}</option>
                {% endfor %}
            </select><br/>
            <input style="text-align:center" type="file" name="file" class="form-control"/><br/>
            <br/>
            <input type="submit" value="Import" class="form-control">
            {% endif %}
        </form>
    </div>
    <div class="brew_extra" id="brew_extra">

    </div>
</div>
{% endblock %}

{% block tb_sidebar_page_main %}
<div class="brew_data" id="brew_data">

</div>
{% endblock %}