brew/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', 'brew.views.brews'),
    url(r'^brews/$', 'brew.views.brews'),
    url(r'^brew_selection/$', 'brew.views.brew_selection'),
    url(r'^brew_data/$', 'brew.views.brew_data'),
    url(r'^brew_delete/(?P<pk>\d+)/$', 'brew.views.brew_delete'),
    url(r'^brews_delete_all/$', 'brew.views.brews_delete_all'),
    url(r'^brews_import/$', 'brew.views.brews_import'),
)

session/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from session.views import SessionView, SessionsView, SessionUpdateView, SessionDeleteView, SessionDetailUpdateView
from session.views import MeasurementListView


urlpatterns = patterns('',
    url(r'^$', SessionsView.as_view()),
    url(r'^sessions/$', SessionsView.as_view()),
    url(r'^sessions/(?P<pk>\d+)/$', SessionsView.as_view()),
    url(r'^workers[/]$', 'session.views.workers', name='workers'),
    url(r'^session_selection/$', 'session.views.session_selection'),
    url(r'^session_available_options/$', 'session.views.session_available_options'),
    url(r'^session_data/$', 'session.views.session_data'),
    url(r'^session_update/(?P<pk>\d+)/$', SessionUpdateView.as_view()),
    url(r'^session_detail_update/(?P<pk>\d+)/$', SessionDetailUpdateView.as_view()),
    url(r'^session_delete/(?P<pk>\d+)/$', SessionDeleteView.as_view()),
    url(r'^session_create/$', 'session.views.session_create'),
    url(r'^session_start/(?P<pk>\d+)/$', SessionView.as_view()),
    url(r'^session_reset/(?P<pk>\d+)/$', 'session.views.session_reset'),
    url(r'^session_archive/(?P<pk>\d+)/$', 'session.views.session_archive'),
    url(r'^session_detail_create/(?P<session_id>\d+)/$', 'session.views.session_detail_create'),
    url(r'^session_detail_start/$', 'session.views.session_detail_start'),
    url(r'^measurements[/]$', MeasurementListView.as_view()),
    url(r'^measurements_clear[/]$', 'session.views.measurements_clear', name='measurements_clear'),
    url(r'^send_master_command/$', 'session.views.send_master_command'),
    url(r'^send_session_detail_command/$', 'session.views.send_session_detail_command'),
    url(r'^send_worker_command/$', 'session.views.send_worker_command'),
    url(r'^session_dashboard/$', 'session.views.session_dashboard'),
    url(r'^session_dashboard_details/$', 'session.views.session_dashboard_details'),
    url(r'^session_work_status/(?P<session_id>\d+)/$', 'session.views.session_work_status'),
    url(r'^worker_available_options/$', 'session.views.worker_available_options'),
    url(r'^workers_info/$', 'session.views.workers_info'),
    url(r'^session_worker_widget/(?P<session_id>\d+)/$', 'session.views.session_worker_widget'),
    url(r'^worker_widget/(?P<worker_id>\d+)/$', 'session.views.worker_widget'),
)

twisted_brew/urls.py
from django.conf.urls import patterns, include, url
from twisted_brew.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^index[/]$', home, name='home'),
    url(r'^home[/]$', home, name='home'),
    url(r'^commands[/]$', commands, name='commands'),
    url(r'^messages[/]$', MessageListView.as_view()),
    url(r'^warnings[/]$', WarningListView.as_view()),
    url(r'^errors[/]$', ErrorListView.as_view()),
    url(r'^messages_clear[/]$', messages_clear, name='messages_clear'),
    url(r'^message_head[/]$', message_head, name='message_head'),
    url(r'^message_rows/(?P<latest_timestamp>\d+)/(?P<max_rows>\d+)[/]$', message_rows, name='message_rows'),
    url(r'^message_delete/(?P<message_id>\d+)[/]$', message_delete, name='message_delete'),
    url(r'^message_fake/(?P<calling_page>\w+)/(?P<message_type>\w+)[/]$', message_fake, name='message_fake'),
    url(r'^charts[/]$', charts, name='charts'),
    url(r'^charts_update[/]$', charts_update, name='charts_update'),
    url(r'^ping_master[/]$', ping_master, name='ping_master'),
    url(r'^fetch_master_info[/]$', fetch_master_info, name='fetch_master_info'),
    url(r'^set_master_info[/]$', set_master_info, name='set_master_info'),
    (r'^brew/', include('brew.urls')),
    (r'^session/', include('session.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Django REST framework
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/', include('twisted_brew.api_v1_urls')),

    # Django Angular test
    url(r'^twistedbrew[/]$', twistedbrew, name='twistedbrew'),
)

session/models.py
from django.db import models
import django.utils.timezone
import brew.models

COLUMN_SMALL_SIZE = 124


class Session(models.Model):
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    session_date = models.DateField(default=django.utils.timezone.now)
    source = models.ForeignKey(brew.models.Brew)
    notes = models.TextField(blank=True)
    locked = models.BooleanField(default=False)
    active_detail = models.ForeignKey('SessionDetail', related_name='session_active_detail', null=True, blank=True)

    def save(self, *args, **kwargs):
        adding = self._state.adding
        models.Model.save(self, *args, **kwargs)
        if self.source and adding:
            index = 1
            for section in self.source.brewsection_set.all():
                for step in section.brewstep_set.all():
                    detail = SessionDetail()
                    detail.session = self
                    detail.name = step.name
                    detail.index = index
                    detail.worker_type = section.worker_type
                    detail.target = step.target
                    detail.hold_time = step.hold_time
                    detail.time_unit_seconds = step.time_unit_seconds
                    detail.notes = section.name
                    detail.done = False
                    detail.skip = False
                    detail.save()
                    index += 1

    def reset(self):
        for detail in self.sessiondetail_set.all():
            detail.assigned_worker = None
            detail.save()
            worker_set = Worker.objects.filter(working_on=detail)
            for worker in worker_set:
                worker.working_on = None
                if worker.status == Worker.BUSY or worker.status == Worker.PAUSED:
                    worker.status = Worker.AVAILABLE
                worker.save()
        self.active_detail = None
        self.save()


    def __str__(self):
        #if self.locked:
        #    status = 'locked'
        #else:
        #    status = 'active'
        #return u'[{1}] {0} ({2})'.format(self.name, self.session_date, status)
        return '[{1}] {0}'.format(self.name, self.session_date)


class SessionDetail(models.Model):
    SECONDS = 1
    MINUTES = 60
    HOURS = 60*MINUTES
    DAYS = 24*HOURS
    HOLD_TIME_UNITS = (
        (SECONDS, 'Seconds'),
        (MINUTES, 'Minutes'),
        (HOURS, 'Hours'),
        (DAYS, 'Days')
    )
    session = models.ForeignKey('Session')
    index = models.IntegerField()
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    worker_type = models.CharField(max_length=COLUMN_SMALL_SIZE)
    target = models.CharField(max_length=COLUMN_SMALL_SIZE)
    hold_time = models.IntegerField(default=1)
    time_unit_seconds = models.IntegerField(choices=HOLD_TIME_UNITS, default=MINUTES)
    notes = models.TextField()
    done = models.BooleanField(default=False)
    assigned_worker = models.ForeignKey('Worker', null=True, default=None, blank=True)

    def display_name(self):
        return self.worker_type.split(".")[-1]

    def begin_work(self, worker_id):
        assigned_worker = Worker.objects.get(pk=worker_id)
        assigned_worker.status = Worker.BUSY
        assigned_worker.working_on = self
        assigned_worker.save()
        self.assigned_worker = assigned_worker
        self.session.active_detail = self
        self.session.save()
        self.save()
        return True

    def end_work(self, cancelled=False):
        if not self.assigned_worker is None:
            self.assigned_worker.status = Worker.AVAILABLE
            self.assigned_worker.working_on = None
            self.assigned_worker.save()
            self.assigned_worker = None
        self.session.active_detail = None
        self.session.save()
        self.done = not cancelled
        self.save()

    def __str__(self):
        return '{0}) {1} [{2}]'.format(self.index, self.name, self.worker_type)


class Worker(models.Model):
    AVAILABLE = 0
    BUSY = 1
    PAUSED = 2
    OFF_LINE = 3
    WORKER_STATUS = (
        (AVAILABLE, 'Available'),
        (BUSY, 'Busy'),
        (PAUSED, 'Paused'),
        (OFF_LINE, 'Off-line'),
    )
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    type = models.CharField(max_length=COLUMN_SMALL_SIZE)
    status = models.IntegerField(choices=WORKER_STATUS, default=AVAILABLE)
    working_on = models.ForeignKey('SessionDetail', null=True, blank=True, default=None)

    @staticmethod
    def enlist_worker(worker_name, worker_type, devices):
        worker_set = Worker.objects.filter(name=worker_name, type=worker_type)
        if len(worker_set) == 0:
            enlisted_worker = Worker()
            enlisted_worker.name = worker_name
            enlisted_worker.type = worker_type
        else:
            enlisted_worker = worker_set[0]
        enlisted_worker.status = Worker.AVAILABLE
        enlisted_worker.save()
        for device in devices:
            check_device = WorkerDevice.objects.filter(worker=enlisted_worker).filter(name=device)
            if len(check_device) == 0:
                add_device = WorkerDevice()
                add_device.name = device
                add_device.worker = enlisted_worker
                add_device.save()
        return enlisted_worker


    @staticmethod
    def take_workers_off_line():
        workers = Worker.objects.filter(status=Worker.AVAILABLE)
        for worker in workers:
            worker.status = Worker.OFF_LINE
            worker.save()

    @staticmethod
    def force_workers_off_line():
        workers = Worker.objects.all()
        for worker in workers:
            worker.status = Worker.OFF_LINE
            worker.save()

    @staticmethod
    def set_worker_status(worker_id, status):
        worker = Worker.objects.get(pk=worker_id)
        if worker is None:
            return False
        worker.status = status
        worker.save()
        return True

    @staticmethod
    def get_worker_status(worker_id):
        worker = Worker.objects.get(pk=worker_id)
        if worker is None:
            return None
        return worker.status

    def __str__(self):
        return '{0} - {1} ({2})'.format(self.name, self.type, Worker.WORKER_STATUS[self.status][1])


class WorkerDevice(models.Model):
    name = models.CharField(max_length=COLUMN_SMALL_SIZE)
    worker = models.ForeignKey(Worker)

    def __str__(self):
        return self.name


class Measurement(models.Model):
    timestamp = models.DateTimeField(auto_now=False)
    session_detail = models.ForeignKey(SessionDetail)
    worker = models.CharField(max_length=COLUMN_SMALL_SIZE)
    device = models.CharField(max_length=COLUMN_SMALL_SIZE)
    value = models.FloatField()
    set_point = models.FloatField()
    work = models.CharField(max_length=COLUMN_SMALL_SIZE)
    remaining = models.CharField(max_length=COLUMN_SMALL_SIZE)

    class Meta:
        ordering = ['-timestamp']

    @staticmethod
    def clear():
        Measurement.objects.all().delete()

    def __str__(self):
        return '{0} [{1}-{2}] {3}'.format(self.timestamp, self.worker, self.device, self.value)

session/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.formsets import formset_factory
from session.models import Session, SessionDetail


class SessionForm(ModelForm):

    class Meta:
        model = Session
        fields = ['name', 'session_date', 'source', 'notes']

    def save(self, commit=True):
        instance = super(ModelForm, self).save(commit=False)
        if commit:
            instance.save()
        return instance


SessionFormSet = formset_factory(SessionForm)


class SessionDetailForm(ModelForm):

    class Meta:
        model = SessionDetail
        fields = ['name', 'worker_type', 'target', 'hold_time', 'time_unit_seconds', 'notes', 'done']

session/templates/measurements.html
{% extends "base.html" %}

{% block content_heading %}
    <h2>{{ heading }}</h2>
{% endblock %}
{% block content %}
{% if object_list %}
    <a class="btn btn-small btn-danger" href="/session/measurements_clear/">
        clear all measurements
    </a>
    <a class="btn btn-small btn-success" href="/session/measurements/">
        refresh measurements
    </a>
    <br />
    <table class="table table-hover">
        <tr>
            <th>Timestamp</th>
            <th>Session Detail</th>
            <th>Worker</th>
            <th>Device</th>
            <th>Value</th>
            <th>Set Point</th>
            <th>Work</th>
            <th>Remaining</th>
        </tr>
        {% for measure in object_list %}
        <tr>
        <td>
            {{ measure.timestamp|date:"G"}}:{{ measure.timestamp|date:"i"}}:{{ measure.timestamp|date:"s"}}
        </td>
        <td>{{ measure.session_detail }}</td>
        <td>{{ measure.worker }}</td>
        <td>{{ measure.device }}</td>
        <td>{{ measure.value }}</td>
        <td>{{ measure.set_point }}</td>
        <td>{{ measure.work }}</td>
        <td>{{ measure.remaining }}</td>
        </tr>
        {% endfor %}
    </table>
    <br />
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"><small>[previous]</small></a>
        {% endif %}
        &nbsp;&nbsp;&nbsp;Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}&nbsp;&nbsp;&nbsp;
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><small>[next]</small></a>
        {% endif %}
    {% endif %}
{% else %}
    <b>No measurements found.</b>
{% endif %}
{% endblock %}

session/templates/session_command_widget.html
<div class="command_widget">
    <button onclick="{{ command }}">{{ command_title }}</button>
</div>

session/templates/session_dashboard.html
{% extends "base.html" %}
{% block extra_head %}
    {% load static %}
    <link href="{% static 'css/session_dashboard.css' %}" rel="stylesheet">
    <script src="{% static 'js/session.js' %}"></script>
    <script src="{% static 'js/session_dashboard.js' %}"></script>
{% endblock %}
{% block content_heading %}
    <h2>Dashboard</h2>
{% endblock %}
{% block content %}
<div id="session">
<!--Session-->
<select id="available_sessions" onchange="get_session_dashboard_details($('#available_sessions').val())">

</select>
<a href="/session/session_dashboard/">
    <small>[refresh]</small>
</a>
<a onclick="get_reset_session($('#available_sessions').val());">
    <small>[reset]</small>
</a>
<a onclick="get_archive_session($('#available_sessions').val());">
    <small>[archive]</small>
</a>
<a onclick="send_master_command('shutdown')">
    <small>[shutdown master]</small>
</a>
{% csrf_token %}
</div>
<div id="session_dashboard_middle">
    <!--<div id="command_widgets" >
        {% include 'session_command_widget.html' with command_title='Pause' command='' %}
        {% include 'session_command_widget.html' with command_title='Resume' command=''  %}
        {% include 'session_command_widget.html' with command_title='Reset' command='' %}
        {% include 'session_command_widget.html' with command_title='Archive' command='' %}
    </div>-->
    <div id="selected_session_details">
        <i>No session found, please create one
            <a href="/session/"><small>[here]</small></a>
        before using the dashboard app</i>
    </div>
    <div id="worker_widgets">
        {% include 'ping_master.html' %}
        <br />
        {% include 'worker_widget.html' with widget_id=1 interval=1000 %}
    </div>
</div>
{% endblock %}
{% block footer %}
{% include 'message_live_feed.html' with count=6 interval=3000 %}
{% endblock %}

session/templates/session_dashboard_details.html
{% load static %}
{% if session %}
<div id="worker_selection">
     <div>
         <p>Select worker</p>
         <p>
             <select id="available_workers">

             </select>
         </p>
         <p>
             <a onclick="start_worker_from_selection()"><small>[start work]</small></a>
             <a onclick="close_worker_selection()"><small>[cancel]</small></a>
         </p>
     </div>
</div>

<table id="session_detail_table" class="table table-hover table-condensed">
    <tr>
        <th>Index</th>
        <th>Name</th>
        <th>Worker</th>
        <th>Target</th>
        <th>Hold</th>
        <th>Time</th>
        <!--<th>Notes</th>-->
        <th>Done</th>
        <th nowrap width="210"><!--Operation--></th>
    </tr>
    {% for detail in session.sessiondetail_set.all %}
        <tr title="{{ detail.notes }}">
            <td>{{ detail.index }}</td>
            <td>{{ detail.name }}</td>
            <td>{{ detail.display_name }}</td>
            <td style="text-align: right;">{{ detail.target }}</td>
            <td style="text-align: right;">{{ detail.hold_time }}</td>
            <td>{{ detail.get_time_unit_seconds_display }}</td>
            <td>
                {% if detail.done %}
                <img style="height: 24px" src="{% static 'img/check.png' %}">
                {% endif %}
            </td>
            <td nowrap>
                <div id="detail_operations_{{ detail.id }}">
                    <div id="operation_assign_worker" class="operation_assign_worker">
                        <a onclick="open_worker_selection({{ detail.id }}, '{{ detail.worker_type }}')">
                            <small>[assign worker]</small>
                        </a>
                    </div>
                    <div id="operation_pause" class="operation_pause">
                        <a onclick="send_detail_command('pause', {{ detail.id }})">
                            <small>[pause]</small>
                        </a>
                    </div>
                    <div id="operation_resume" class="operation_resume">
                         <a onclick="send_detail_command('resume', {{ detail.id }})">
                             <small>[resume]</small>
                         </a>
                    </div>
                    <div id="operation_reset" class="operation_reset">
                        <a onclick="send_detail_command('reset', {{ detail.id }})">
                            <small>[reset]</small>
                        </a>
                    </div>
                </div>
            </td>
        </tr>
    {% empty %}
    <li>No session details found</li>
    {% endfor %}
</table>
{% else %}
Session not found
{% endif %}

session/templates/session_delete.html
<a onclick="get_session_data({{ object.pk }})">
    <small>[back]</small>
</a>
<br/>
<form action="/session/session_delete/{{ object.pk }}/" method="POST">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

session/templates/session_detail_create.html
{% extends "base.html" %}

{% block content_heading %}
<h2>Session Detail for {{ session.name }}</h2>
{% endblock %}

{% block content %}
<form action="/session/session_detail_create/{{ session.id }}/" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" name="submit" value="Create Detail">
</form>
<br/>
{% endblock %}

session/templates/session_detail_update.html
<a href="/session/sessions/{{ object.session.pk }}">
    <small>[back]</small>
</a>
<br/>
<form action="/session/session_detail_update/{{ object.pk }}/" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <br />
    <input type="submit" value="Update" />
</form>

session/templates/session_selection.html
<a class="btn btn-xs btn-default" onclick="get_create_session()">
    create
</a>
<br />
<b>Available sessions</b>
<ul>
    {% for detail in selection %}
    {% if not detail.locked %}
    <li><a onclick="get_session_data({{ detail.pk }})">{{ detail }}</a></li>
    {% endif %}
    {% empty %}
    <li>No sessions found</li>
    {% endfor %}
</ul>
<b>Archived sessions</b>
<ul>
    {% for detail in selection %}
    {% if detail.locked %}
    <li><a onclick="get_session_data({{ detail.pk }})">{{ detail }}</a></li>
    {% endif %}
    {% empty %}
    <li>No sessions found</li>
    {% endfor %}
</ul>
<br />
<br />
<br />
<br />
<br />
{% if init_selection > 0 %}
<script type="text/javascript">
    get_session_data({{ init_selection }});
</script>
{% endif %}

session/templates/session_start.html
{% extends "base.html" %}
{% block extra_head %}
{% load static %}
    <script src="{% static 'js/session.js' %}"></script>
    <script src="{% static 'js/session_start.js' %}"></script>
{% endblock %}
{% block content_heading %}
<h2>Session Execution</h2>
{% csrf_token %}
{% endblock %}

{% block content %}
<a href="/session/sessions/{{ object.id }}/">
    <small>[back]</small>
</a>
<a onclick="get_update_session({{ object.id }})">
    <small>[update]</small>
</a>
<a onclick="get_delete_session({{ object.id }})">
    <small>[delete]</small>
</a>
<br/>
<b>{{ object.name }}
    <small>
        {% if object.locked %}
        [locked]
        {% else %}
        [active]
        {% endif %}
    </small>
</b>
<table>
    <tr>
        <td><b>Date:</b></td>
        <td>{{ object.session_date }}</td>
    </tr>
    <tr>
        <td><b>Source:</b></td>
        <td>{{ object.source }}</td>
    </tr>
    <tr>
        <td><b>Notes:</b></td>
        <td>{{ object.notes }}</td>
    </tr>
</table>
<br/>
<h3>Details</h3>
{% if not object.locked %}
<a href="/session/session_detail_create/{{ object.id }}/">
    <small>[create]</small>
</a>
<a href="/session/session_start/{{ object.id }}/">
    <small>[refresh]</small>
</a>
{% endif %}
<ul>
    {% for detail in details %}
    <li>{{ detail }}
        <select id="detail_worker{{ detail.id }}">
            {% for worker in workers %}
            {% if worker == detail.worker_type %}
            <option value="{{ worker.id }}">{{ worker.name }}</option>
            {% endif %}
            {% empty %}
            <option value="0">-No worker available-</option>
            {% endfor %}
            <option value="0">-Not available-</option>
        </select>
        <a onclick="start_session_detail($('#detail_worker{{ detail.id }}').val(),{{ detail.id }})"><small>[start]</small></a>
        <a onclick="send_worker_command('pause', $('#detail_worker{{ detail.id }}').val())"><small>[pause]</small></a>
        <a onclick="send_worker_command('resume', $('#detail_worker{{ detail.id }}').val())"><small>[resume]</small></a>
        <a onclick="send_worker_command('reset', $('#detail_worker{{ detail.id }}').val())"><small>[reset]</small></a>
        {% empty %}
    <li>No details available.</li>
    {% endfor %}
</ul>

{% endblock %}

session/templates/session_update.html
<a href="/session/sessions/{{ object.pk }}">
    <small>[back]</small>
</a>
<br/>
<form action="/session/session_update/{{ object.pk }}/" method="POST">{% csrf_token %}
    {{ form.as_table }}
    <br />
    <input type="submit" value="Update" />
</form>

session/templates/sessions.html
{% extends "base.html" %}
{% block extra_head %}
{% load static %}
    <link href="{% static 'css/session.css' %}" rel="stylesheet">
    <script src="{% static 'js/session.js' %}"></script>
    <script src="{% static 'js/sessions.js' %}"></script>
{% endblock %}
{% block content_heading %}
<h2>Sessions</h2>
{% csrf_token %}
<input type="hidden" value="{{selection}}" id="init_brew_selection" name="init_brew_selection">
{% endblock %}
{% block tb_sidebar_page_sidebar %}
<div class="session_selection" id="session_selection">

</div>
{% endblock %}

{% block tb_sidebar_page_main %}
<div class="session_data" id="session_data">

</div>
{% endblock %}

session/templates/worker_widget.html
{% load static %}
<script type="text/javascript">
    var worker_widget_interval = {{ interval }};
</script>
<link href="{% static 'css/worker_widget.css' %}" rel="stylesheet">
<script src="{% static 'js/session_worker_widget.js' %}"></script>

<div id="worker_widget_{{ widget_id }}" class="worker_widget">
<i>No work in progress</i>
</div>

session/templates/worker_widget_data.html
<table>
    <tr>
        <td align="center"><b>{{ session_detail.name }}</b></td>
    </tr>
    <tr>
        <td align="center"><i>{{ worker.name }}</i></td>
    </tr>
    {% for last_measurement in last_measurements %}
    <tr>
        <td align="center">{{ last_measurement.work }}</td>
    </tr>
    <tr>
        <td align="center">{{ last_measurement.remaining }}</td>
    </tr>
    {% empty %}
    <tr><td align="center"><i>No work in progress</i></td></tr>
    {% endfor %}
</table>

session/templates/workers.html
{% extends "base.html" %}

{% block content_heading %}
    {% load static %}
    <script type="text/javascript">
        var interval = 3000;
    </script>
    <link href="{% static 'css/worker_widget.css' %}" rel="stylesheet">
    <script src="{% static 'js/worker_widget.js' %}"></script>
    <h2>Workers</h2>
{% endblock %}
{% block content %}
        <a class="btn btn-small btn-danger" href="/session/workers_info/">
        reregister all workers
        </a>
        <ul>
            {% for worker in workers %}
            <li>{{ worker }}</li>
            <ul>
                {% for device in worker.workerdevice_set.all %}
                <li>{{ device.name }} {{ device.io }}</li>
                {% endfor %}
            </ul>
            {% if worker.working_on %}
            {% include 'worker_widget.html' with widget_id=1 interval=1000 %}
            <script type="text/javascript">
                $(function() {
                    var active_worker_widget_{{ worker.id }} = new WorkerWidget( {{ worker.id }}, interval);
                    active_worker_widget_{{ worker.id }}.run();
                });
            </script>
            <div id="worker_widget_{{ worker.id }}" class="worker_widget">
            {% endif %}
            {% empty %}
            <li>No workers found.</li>
            {% endfor %}
        </ul>
{% endblock %}